### ISSUE TITLE
flutter upgrade to 1.9.1+hotfix.2, chose image app crashed

### ISSUE THREAD

**Issue by jsu93** [hnvn/flutter_image_cropper#75]
```
I/art     (27536): Rejecting re-init on previously-failed class java.lang.Class<androidx.activity.ComponentActivity$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/LifecycleEventObserver;
I/art     (27536):   at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
I/art     (27536):   at android.app.Activity android.app.Instrumentation.newActivity(java.lang.ClassLoader, java.lang.String, android.content.Intent) (Instrumentation.java:1083)
I/art     (27536):   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2682)
I/art     (27536):   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2864)
I/art     (27536):   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art     (27536):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1567)
I/art     (27536):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
I/art     (27536):   at void android.os.Looper.loop() (Looper.java:156)
I/art     (27536):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6577)
I/art     (27536):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     (27536):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:941)
I/art     (27536):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:831)
I/art     (27536): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.LifecycleEventObserver" on path: DexPathList[[zip file "/data/app/com.im.kchat-1/base.apk"],nativeLibraryDirectories=[/data/app/com.im.kchat-1/lib/arm, /data/app/com.im.kchat-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
I/art     (27536):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
I/art     (27536):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
I/art     (27536):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/art     (27536):   at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
I/art     (27536):   at android.app.Activity android.app.Instrumentation.newActivity(java.lang.ClassLoader, java.lang.String, android.content.Intent) (Instrumentation.java:1083)
I/art     (27536):   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2682)
I/art     (27536):   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2864)
I/art     (27536):   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art     (27536):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1567)
I/art     (27536):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
I/art     (27536):   at void android.os.Looper.loop() (Looper.java:156)
I/art     (27536):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6577)
I/art     (27536):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     (27536):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:941)
I/art     (27536):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:831)
I/art     (27536):
I/art     (27536): Rejecting re-init on previously-failed class java.lang.Class<androidx.activity.ComponentActivity$3>: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/LifecycleEventObserver;
I/art     (27536):   at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
I/art     (27536):   at android.app.Activity android.app.Instrumentation.newActivity(java.lang.ClassLoader, java.lang.String, android.content.Intent) (Instrumentation.java:1083)
I/art     (27536):   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2682)
I/art     (27536):   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2864)
I/art     (27536):   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art     (27536):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1567)
I/art     (27536):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
I/art     (27536):   at void android.os.Looper.loop() (Looper.java:156)
I/art     (27536):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6577)
I/art     (27536):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     (27536):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:941)
I/art     (27536):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:831)
I/art     (27536): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.LifecycleEventObserver" on path: DexPathList[[zip file "/data/app/com.im.kchat-1/base.apk"],nativeLibraryDirectories=[/data/app/com.im.kchat-1/lib/arm, /data/app/com.im.kchat-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
I/art     (27536):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
I/art     (27536):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
I/art     (27536):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/art     (27536):   at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
I/art     (27536):   at android.app.Activity android.app.Instrumentation.newActivity(java.lang.ClassLoader, java.lang.String, android.content.Intent) (Instrumentation.java:1083)
I/art     (27536):   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2682)
I/art     (27536):   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2864)
I/art     (27536):   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art     (27536):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1567)
I/art     (27536):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
I/art     (27536):   at void android.os.Looper.loop() (Looper.java:156)
I/art     (27536):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6577)
I/art     (27536):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     (27536):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:941)
I/art     (27536):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:831)
I/art     (27536):
I/art     (27536): Rejecting re-init on previously-failed class java.lang.Class<androidx.activity.ImmLeaksCleaner>: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/LifecycleEventObserver;
I/art     (27536):   at java.lang.Object java.lang.Class.newInstance!() (Class.java:-2)
I/art     (27536):   at android.app.Activity android.app.Instrumentation.newActivity(java.lang.ClassLoader, java.lang.String, android.content.Intent) (Instrumentation.java:1083)
I/art     (27536):   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2682)
I/art     (27536):   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2864)
I/art     (27536):   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art     (27536):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1567)
I/art     (27536):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
I/art     (27536):   at void android.os.Looper.loop() (Looper.java:156)
I/art     (27536):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6577)
I/art     (27536):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     (27536):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:941)
I/art     (27536):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:831)
I/art     (27536): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.LifecycleEventObserver" on path: DexPathList[[zip file "/data/app/com.im.kchat-1/base.apk"],nativeLibraryDirectories=[/data/app/com.im.kchat-1/lib/arm, /data/app/com.im.kchat-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]

```

**Comment by originlan** [comment]
I have the same problem

**Comment by originlan** [comment]
I took a look at it. The original ucrop:2.2.3 updates the adaption of Androidx, and the parameter of start becomes AppCompatActivity, but the callback parameter of the channel of flutter is activity, so there is no solution at present

**Comment by hnvn** [comment]
I'll have a look at it

**Comment by originlan** [comment]
thank u

**Comment by hnvn** [comment]
I've just published v1.1.0, it is expected to resolve this issue and a big update for this plugin as well (especially for UI customization).

**Comment by faniuy** [comment]
still has the same issue after upgraded to 1.1.0
`Rejecting re-init on previously-failed class java.lang.Class<androidx.activity.ComponentActivity$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/LifecycleEventObserver;`

**Comment by dop3ch3f** [comment]
Same here as well. what do you suggest i do to fix this issue at least

**Comment by melvinm99** [comment]
Same for me

**Comment by hnvn** [comment]
What about this:
```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by dop3ch3f** [comment]
@hnvn i have done this as well

**Comment by dop3ch3f** [comment]
`Rejecting re-init on previously-failed class java.lang.Class<androidx.activity.ComponentActivity$2>
D/AndroidRuntime(  983): Shutting down VM
E/AndroidRuntime(  983): FATAL EXCEPTION: main
E/AndroidRuntime(  983): Process: com.ecodeem.ecodeem, PID: 983
E/AndroidRuntime(  983): java.lang.NoClassDefFoundError: androidx.activity.ComponentActivity$2
E/AndroidRuntime(  983): 	at androidx.activity.ComponentActivity.<init>(ComponentActivity.java:94)
E/AndroidRuntime(  983): 	at androidx.fragment.app.FragmentActivity.<init>(FragmentActivity.java:127)
E/AndroidRuntime(  983): 	at androidx.appcompat.app.AppCompatActivity.<init>(AppCompatActivity.java:77)
E/AndroidRuntime(  983): 	at com.yalantis.ucrop.UCropActivity.<init>(UCropActivity.java:63)
E/AndroidRuntime(  983): 	at java.lang.Class.newInstance(Native Method)
E/AndroidRuntime(  983): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
E/AndroidRuntime(  983): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
E/AndroidRuntime(  983): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
E/AndroidRuntime(  983): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
E/AndroidRuntime(  983): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
E/AndroidRuntime(  983): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(  983): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(  983): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E/AndroidRuntime(  983): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(  983): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime(  983): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`
this is what i get as soon as i call the cropper with the new values of the version 1.1.0.

These are my parameters:
File cropped = await ImageCropper.cropImage(
        sourcePath: _imageFile.path,
        maxWidth: 2000,
        maxHeight: 1000,
        aspectRatioPresets: [
          CropAspectRatioPreset.square,
          CropAspectRatioPreset.ratio3x2,
          CropAspectRatioPreset.original,
          CropAspectRatioPreset.ratio4x3,
          CropAspectRatioPreset.ratio16x9
        ],
        compressQuality: 100,
        androidUiSettings: AndroidUiSettings(
          toolbarTitle: "Crop Image",
          toolbarColor: Colors.white,
          toolbarWidgetColor: HexColor(main_color), // ignore the hexColor it just resolves to color from a hexcode
          statusBarColor: Colors.white,
          backgroundColor: Colors.black,
          activeControlsWidgetColor: HexColor(main_color),
          activeWidgetColor: HexColor(main_color),
          cropFrameColor: HexColor(main_color),
          initAspectRatio: CropAspectRatioPreset.original,
          lockAspectRatio: false,
        ),
        iosUiSettings: IOSUiSettings(),
      );

**Comment by melvinm99** [comment]
I get this error too

**Comment by melvinm99** [comment]
I could solve it only creating a new flutter project and copying libs and assets

**Comment by veicn** [comment]
remove app build.gradle this code:
    rootProject.allprojects {
        project.configurations.all {
            resolutionStrategy.eachDependency { details ->
                if (details.requested.group == 'androidx.core') {
                    details.useVersion "1.0.1"
                }
                if (details.requested.group == 'androidx.lifecycle') {
                    details.useVersion "2.0.0"
                }
                if (details.requested.group == 'androidx.versionedparcelable') {
                    details.useVersion "1.0.0"
                }
            }
        }
    }

**Comment by meetbb** [comment]
> remove app build.gradle this code:
> `rootProject.allprojects { project.configurations.all { resolutionStrategy.eachDependency { details -> if (details.requested.group == 'androidx.core') { details.useVersion "1.0.1" } if (details.requested.group == 'androidx.lifecycle') { details.useVersion "2.0.0" } if (details.requested.group == 'androidx.versionedparcelable') { details.useVersion "1.0.0" } } } }`

This solution worked like a charm for me.
